apiVersion: v1
kind: Service
metadata:
  name: my-node-ingress-service
spec:
  selector:
    app: my-node-ingress
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-ingress-deployment
spec:
  selector:
    matchLabels:
      app: my-node-ingress
  template:
    metadata:
      labels:
        app: my-node-ingress
    spec:
      containers:
        - name: my-node-ingress
          image: chlebq/my-node-ingress
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000