apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sugary-fruits
spec:
  broker: default
  filter:
    attributes:
      type: low-sugar
      #type: medium-sugar
      #type: high-sugar
      # uncomment this if you don't want event message filtering
      #type: ""
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: fruit-events-display # TODO change this to your service name
